var quizLessonBoth = "lesson";var lessonNumber = 43;var numOfAllQuiz = 45;var lessonTitle = "Les pronoms réfléchis I (Reflexive pronouns)";var btnColor = ["#1EEC00","#163F00","#90E700","#254800"];var quesToRemove = [];var startNarration = ["Have you ever seen a French verb with S.E. in front and wondered what that was?","S.E. in front of a verb means that a reflexive pronoun is required in the conjugation.","Reflexive pronouns mean that the action is done to oneself, for example, "+'"'+"LAVER"+'"'+" means "+'"'+"to wash"+'"'+", whereas "+'"'+"SE LAVER"+'"'+" means "+'"'+"to wash oneself"+'"'+".","In French, many verbs have to include "+'"'+"SE"+'"'+" and sometimes, verbs require it even if in English, adding "+'"'+"oneself"+'"'+" would make no sense at all!","Just remember that when S.E. is in front of a verb, it has to be conjugated differently... Let's take a look."];var narration = ["","","","",""];var titleSkip = [false,false,false,false];var forTitles = ["Me","Te","Se"];var engTitles = ["Myself","Yourself","Himself / Herself"];var forSideTitles = ["Me","Te","Se"];var engSideTitles = ["Myself","Yourself","Himself / Herself"];var exampleNums = [3,3,3];var forExamples = ["Je <strong>m'</strong>habille pour aller à l'école.","Je <strong>me</strong> couche plus tard que lui.","Je <strong>me</strong> repose sur le gazon.","%The conjugation ''assieds'' could also be used instead of ''assois'', they are simply two alternate versions.%Tu <strong>t'</strong>assois pour lire.","Est-ce que tu <strong>te</strong> souviens?","Tu <strong>t'</strong>es fait mal.","Il <strong>se</strong> lave dans le bain.","Il <strong>se</strong> brosse les cheveux.","Il <strong>se</strong> réveille très tôt."];var engExamples = ["I am getting (<em>myself</em>) dressed for school.","I go to bed (<em>myself</em>) later than him. ","I am resting (<em>myself</em>) on the grass.","You are sitting (<em>yourself</em>) down to read.","Do you (<em>yourself</em>) remember?","You hurt <em>yourself</em>. ","He is washing <em>himself</em> in the bath.","He is brushing his hair. (Literal: He is brushing <em>himself</em> the hair.)","He wakes (<em>himself</em>) up very early."];


var forExtra1 = ["Je <strong>m'</strong>étire avant de courir.","Non, c'est tout ce dont je <strong>me</strong> souviens.","Je suis ton père. Je <strong>m'</strong>inquiète pour toi.","Je travaille, ensuite je <strong>me</strong> repose.","C'est ce que je <strong>me</strong> disais...","Je <strong>me</strong> suis assis ici pour parler au téléphone.","Je <strong>me</strong> réveillais toujours avant lui.","J'ai pris ma douche et ensuite je <strong>me</strong> suis habillée.","Je <strong>me</strong> reposais sur un matelas gonflable.","Je <strong>me</strong> suis rapproché de la cheminée, parce que j'avais froid.","Maman ne me trouvait pas, parce que je <strong>me</strong> cachais dans les feuilles."];var engExtra1 = ["I stretch <em>myself</em> before running.","No, that's all I remember (<em>myself</em>).","I am your father. I worry (<em>myself</em>) about you.","I work, then I rest (<em>myself</em>).","That's what I was telling <em>myself</em>...","I sat (<em>myself</em>) here to talk on the phone.","I used to always wake (<em>myself</em>) up before him.","I took a shower and then I got (<em>myself</em>) dressed.","I was resting (<em>myself</em>) on an inflatable mattress.","I moved (<em>myself</em>) closer to the fireplace, because I was cold.","Mommy couldn't find me, because I was hiding (<em>myself</em>) in the leaves."];var imageExtra1 = ["../../block/24/images/pic2.jpg","../../convo/images/convo51B.jpg","../../convo/images/convo53A.jpg","../../block/10/images/pic2.jpg","../../convo/images/convo28B.jpg","../../verb/86/images/pic3.jpg","../../verb/106/images/pic4.jpg","../../block/10/images/pic1.jpg","../../verb/80/images/pic4.jpg","../../verb/134/images/pic1.jpg","../../verb/43/images/pic4.jpg"];var fastExtra1 = ["../../block/24/sounds/sound3","../../convo/51/sounds/2fast9","../../convo/53/sounds/1fast3","../../block/10/sounds/sound3","../../convo/28/sounds/2fast8","../../verb/86/sounds/sound11","../../verb/106/sounds/sound15","../../block/10/sounds/sound1","../../verb/80/sounds/sound15","../../verb/134/sounds/sound3","../../verb/43/sounds/sound15"];var slowExtra1 = ["../../block/24/sounds/sound4","../../convo/51/sounds/2slow9","../../convo/53/sounds/1slow3","../../block/10/sounds/sound4","../../convo/28/sounds/2slow8","../../verb/86/sounds/sound12","../../verb/106/sounds/sound16","../../block/10/sounds/sound2","../../verb/80/sounds/sound16","../../verb/134/sounds/sound4","../../verb/43/sounds/sound16"];

var forExtra2 = ["Tu es toujours heureuse quand tu <strong>te</strong> réveilles.","Tu <strong>te</strong> reposerais si tu avais moins de travail à faire.","Tu <em>te</em> réveillerais moins fatiguée si tu <strong>te</strong> couchais plus tôt."];

var engExtra2 = ["You are always happy when you wake (<em>yourself</em>) up. <i class='qhint'>(informal)</i>","You would rest (<em>yourself</em>) if you had less work to do. <i class='qhint'>(informal)</i>","You would wake (<em>yourself</em>) up less tired if you went to bed (<em>yourself</em>) earlier. <i class='qhint'>(informal)</i>"];

var imageExtra2 = ["../../verb/106/images/pic2.jpg","../../verb/80/images/pic6.jpg","../../verb/106/images/pic6.jpg"];var fastExtra2 = ["../../verb/106/sounds/sound7","../../verb/80/sounds/sound23","../../verb/106/sounds/sound23"];var slowExtra2 = ["../../verb/106/sounds/sound8","../../verb/80/sounds/sound24","../../verb/106/sounds/sound24"];


var forExtra3 = ["Il <strong>se</strong> rase avant de prendre sa douche.","Elle <strong>se</strong> cache derrière le parapluie.","Il <strong>se</strong> couche après avoir lu un peu.","Elle <strong>se</strong> réveille vers six heures trente.","Il <strong>se</strong> repose après une longue journée de travail.","Il <strong>s'</strong>habillerait tout seul, mais il ne sait pas faire un noeud de cravate."];


var engExtra3 = ["He shaves (<em>himself</em>) before taking a shower.","She is hiding (<em>herself</em>) behind the umbrella.","He goes to sleep (<em>himself</em>) after having read a bit.","She wakes (<em>herself</em>) up at around six thirty.","He is resting (<em>himself</em>) after a long day of work.","He would get dressed all by <em>himself</em>, but he doesn't know how to tie a tie."];var imageExtra3 = ["../../block/24/images/pic3.jpg","../../block/24/images/pic14.jpg","../../block/24/images/pic10.jpg","../../block/23/images/pic7.jpg","../../block/24/images/pic11.jpg","../../verb/47/images/pic6.jpg"];var fastExtra3 = ["../../block/24/sounds/sound5","../../block/24/sounds/sound27","../../block/24/sounds/sound19","../../block/23/sounds/sound13","../../block/24/sounds/sound21","../../verb/47/sounds/sound23"];var slowExtra3 = ["../../block/24/sounds/sound6","../../block/24/sounds/sound28","../../block/24/sounds/sound20","../../block/23/sounds/sound14","../../block/24/sounds/sound22","../../verb/47/sounds/sound24"];